name: Continuos Integration

on:
  pull_request:
    types: [opened, synchronize]
  workflow_call:
    

jobs:
  Lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Install dependencies
        run: npm install
      - name: Lint sources
        run: npm run lint
  
  Tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Install dependencies
        run: npm install
      - name: Test application
        run: npm test